In [7]:
import pandas as pd
import numpy as np

In [12]:
df=pd.read_csv("KNN_Neighbors.csv", sep=";")

In [13]:
df

age  Income(k)
0   21         60
1   20         55
2   22         60
3   22         61
4   23         65
5   21         62
6   25         65

In [66]:
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor(n_neighbors=3)
knn.fit(df[['age']],df[['Income(k)']])

KNeighborsRegressor(n_neighbors=3)

# Predict the value of (income) when given x=22

In [67]:
predict_KNN=knn.predict([[22]])

C:\Users\Shimul\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


In [68]:
predict_KNN

array([[60.33333333]])

# Compare KNN Algorithm and Linear Regression

In [69]:
from sklearn.linear_model import LinearRegression
l_reg=LinearRegression()

In [70]:
l_reg.fit(df[['age']], df[['Income(k)']])

LinearRegression()

In [71]:
l_prediction=l_reg.predict([[22]])

C:\Users\Shimul\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [72]:
l_prediction

array([[61.14285714]])

#Difference between two outcome KNN vs Linear Regression

In [73]:
abs(predict_KNN-l_prediction)

array([[0.80952381]])

In [74]:
df

age  Income(k)  KNN_Predict  Li_Predict
0   21         60    60.666667   59.392857
1   20         55    59.000000   57.642857
2   22         60    60.333333   61.142857
3   22         61    60.333333   61.142857
4   23         65    62.000000   62.892857
5   21         62    60.666667   59.392857
6   25         65    63.333333   66.392857

# Extra Try for Whole Data set

In [75]:
df['KNN_Predict']=knn.predict(df[['age']])

In [78]:
knn_al=df['KNN_Predict']=knn.predict(df[['age']])
df

age  Income(k)  KNN_Predict  Li_Predict
0   21         60    60.666667   59.392857
1   20         55    59.000000   57.642857
2   22         60    60.333333   61.142857
3   22         61    60.333333   61.142857
4   23         65    62.000000   62.892857
5   21         62    60.666667   59.392857
6   25         65    63.333333   66.392857

In [76]:
lin=df['Li_Predict']=l_reg.predict(df[['age']])

In [63]:
df

age  Income(k)  KNN_Predict  Li_Predict
0   21         60    60.666667   59.392857
1   20         55    59.000000   57.642857
2   22         60    60.333333   61.142857
3   22         61    60.333333   61.142857
4   23         65    62.000000   62.892857
5   21         62    60.666667   59.392857
6   25         65    63.333333   66.392857

In [46]:
lin

array([[59.39285714],
       [57.64285714],
       [61.14285714],
       [61.14285714],
       [62.89285714],
       [59.39285714],
       [66.39285714]])

#Comparison whole Dataset

In [79]:
df['KNN vs Lin']=abs(knn_al-lin)

In [80]:
df

age  Income(k)  KNN_Predict  Li_Predict  KNN vs Lin
0   21         60    60.666667   59.392857    1.273810
1   20         55    59.000000   57.642857    1.357143
2   22         60    60.333333   61.142857    0.809524
3   22         61    60.333333   61.142857    0.809524
4   23         65    62.000000   62.892857    0.892857
5   21         62    60.666667   59.392857    1.273810
6   25         65    63.333333   66.392857    3.059524

In [81]:
df.to_excel("KNN_Excel.xlsx", index=False)